title: Math Notes
description: A collection of mathematical notes and concepts
theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  parse_block_html: true
